/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RWAToken } from './RWAToken.js';
export * as factories from './factories/index.js';
export { RWAToken__factory } from './factories/RWAToken__factory.js';