/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { RWAToken__factory } from './RWAToken__factory.js';
export { Treasury__factory } from './Treasury__factory.js';